### ISSUE TITLE
Convert Template Hierarchy Lesson Plan

### ISSUE THREAD

**Issue by JulieKuehl** [wptrainingteam/template-heirarchy#1]
Convert Lesson Plan to GitHub

- [x]  copy and paste from Make site
- [ ]  clean up the Markdown
- [ ]  download the old images
- [ ]  upload the images into GitHub
- [ ]  swap out the image links

**Comment by JulieKuehl** [comment]
https://make.wordpress.org/training/handbook/theme-school/template-hierarchy/

**Comment by man4toman** [comment]
[Update] Convert Lesson Plan to GitHub

- [ X ] copy and paste from Make site
- [ X ] clean up the Markdown
- [ X ] download the old images
- [ X ] upload the images into GitHub
- [ X ] swap out the image links

**Comment by man4toman** [comment]
- [x ] clean

**Comment by man4toman** [comment]
[X] clean

**Comment by man4toman** [comment]
Convert Lesson Plan to GitHub
 [x]   copy and paste from Make site
 [ ]   clean up the Markdown
 [ ]   download the old images
 [ ]   upload the images into GitHub
 [ ]   swap out the image links

**Comment by man4toman** [comment]
[Update]Convert Lesson Plan to GitHub

- [x]   copy and paste from Make site
- [x]   clean up the Markdown
- [x]   download the old images
- [x]   upload the images into GitHub
- [x]   swap out the image links

Related PR: #6
